export struct ResultRow {
    name: string,
    description: string,
    year: string,
    manufacturer: string,
    category: string,
    status: string,
    // 0=OK, 1=Manquante, 2=Corrompue, 3=Non référencée, 4=Non scannée
    status-kind: int,
    action: string,
    crc: string,
    size: string,
}

export struct PluginRow {
    id: string,
    name: string,
    console-family: string,
    version: string,
    status-text: string,
    status-kind: int,
    is-header: bool,
}

export struct SystemOption {
    id: string,
    name: string,
    console-family: string,
    is-header: bool,
}
